site_name: Blockchain
site_url: https://blockchain.andstuff.club
site_author: nyg
site_description: Blockchain-related writings

repo_name: nyg/smart-contracts
repo_url: https://github.com/nyg/smart-contracts

extra_css:
  - assets/custom.css

extra:
  analytics:
    provider: goatcounter

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences

plugins:
  - search
  - tags:
      tags_file: tags.md
  - git-revision-date-localized:
      enable_creation_date: true
      type: custom
      custom_format: "%b %-d, ’%y"
      exclude:
        - index.md
        - tags.md

theme:
  name: material
  custom_dir: overrides
  language: custom
  features:
    #- navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo

nav:
  - Home:
    - Welcome: index.md
    - Tags: tags.md
